packages:
  - ccalm-web
  - ccalm-api

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - pg-protocol@1.16.0
  - pg@8.23.0
  - sonner@2.0.8
